name: jobsearch_server
description: Server side for jobsearch project
version: 0.0.1
author: Dmitriy <dmytro.koval@nure.ua>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.3.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0